name: Reusable Github Actions - Demo

run-name: Github Reusable Workflow

on:
  workflow_call:
    inputs:
      DAY_OF_WEEK:
        required: true
        type: string
        default: "Tuesday"

jobs:
  called-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Print the git version
        run: |
          git --version

      - name: Clone the Github Repository
        run: |
          git clone https://${{ secrets.ORG_GITHUB_TOKEN }}@github.com/cloudhonk/ga-flow-central
          ls ga-flow-central

      - name: Print the environment variables
        run: |
          echo ${{ inputs.DAY_OF_WEEK }}
